version: 2

models:

  - name: stg_addresses  
    columns:
      - name: address_id
        tests:
          - not_null
          - unique

  - name: stg_events
    columns:
      - name: event_id
        tests:
          - not_null
          - unique

  - name: stg_order_items
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests: 
          - not_null
      - name: quantity
        tests:
          - positive_values

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: user_id
        tests:
          - not_null
      - name: order_cost
        tests:
          - positive_values
      - name: order_total
        tests:
          - positive_values        

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
      - name: product_price
        tests:
          - positive_values

  - name: stg_promos
    columns:
      - name: promo_id
        tests:
          - not_null
          - unique

  - name: stg_users
    columns:
      - name: user_id
        tests:
          - not_null
          - unique
